version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    ports:
      - "5432:5432"

   web:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/plookjing
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_HOST: db
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/plookjing
    ports:
      - "8888:8888"
    command: >
      python manage.py shell_plus --notebook -- --allow-root --ip=0.0.0.0 --NotebookApp.token=""
    depends_on:
      - db

volumes:
  db_data:
